// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28IA1hG9jx2bEZrKTiLR8Zhvj_cg19Xk',
    appId: '1:940570438065:android:2cec176b1b02402f997590',
    messagingSenderId: '940570438065',
    projectId: 'ai-chat-1859d',
    storageBucket: 'ai-chat-1859d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRQ47ed4xKF4_bQQ1jrjZgy2ZLBT78zU',
    appId: '1:940570438065:ios:2ebf9e4c35b2e31a997590',
    messagingSenderId: '940570438065',
    projectId: 'ai-chat-1859d',
    storageBucket: 'ai-chat-1859d.appspot.com',
    iosBundleId: 'com.example.googleAiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIjg8ITydaIQr7FdhU2_dLcLS-iLa5oSs',
    appId: '1:940570438065:web:4ca04d693ec541ab997590',
    messagingSenderId: '940570438065',
    projectId: 'ai-chat-1859d',
    authDomain: 'ai-chat-1859d.firebaseapp.com',
    storageBucket: 'ai-chat-1859d.appspot.com',
    measurementId: 'G-L70T3XVS52',
  );
}
